/* import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Informes de Cementerio",
  description: "Generated by Gilson ALbino Barbosa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
       <script async src="https://docs.opencv.org/4.x/opencv.js" />
      <body className={inter.className}>{children}</body>
    </html>
  );
} */ 

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/nivelApp/SidebarContext"; // Importa tu contexto

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Informes de Cementerio",
  description: "Generated by Gilson Albino Barbosa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <SidebarProvider>
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}